// Sync script: reads .claude/skills/nehroai-admin/SKILL.md and writes a
// committed TypeScript constant module so the skill content can be served over
// HTTP without relying on runtime file reads (Turbopack/Vercel unreliable).
//
// Usage: pnpm skill:sync

import * as fs from 'node:fs';
import * as path from 'node:path';

const root = process.cwd();
const skillPath = path.join(root, '.claude', 'skills', 'nehroai-admin', 'SKILL.md');
const outPath = path.join(root, 'lib', 'admin', 'skill-guide.ts');

// --- Read source ----------------------------------------------------------------

const raw = fs.readFileSync(skillPath, 'utf-8');

// --- Parse frontmatter ----------------------------------------------------------
// Minimal hand-rolled parser for the YAML block at the top of the file.
// Supports:
//   name: some-string
//   description: >
//     multi-line indented block scalar (YAML block folded `>`)

function parseFrontmatter(content: string): { name: string; description: string } {
  // Extract between opening `---` and closing `---`
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) throw new Error('No YAML frontmatter found in SKILL.md');
  const yaml = match[1];

  // Extract `name:`
  const nameMatch = yaml.match(/^name:\s*(.+)$/m);
  if (!nameMatch) throw new Error('No `name:` field in frontmatter');
  const name = nameMatch[1].trim();

  // Extract `description:` — may be a plain inline value OR a block scalar (`>`)
  // spanning multiple indented lines.
  const descMatch = yaml.match(/^description:\s*(.*)$/m);
  if (!descMatch) throw new Error('No `description:` field in frontmatter');

  let description: string;
  const inline = descMatch[1].trim();

  if (inline === '>') {
    // Block scalar — collect following lines that are indented (relative to
    // the root level of the YAML).  Each line is trimmed and joined with a
    // space; trailing blank lines are discarded.
    const afterDesc = yaml.slice(yaml.indexOf(descMatch[0]) + descMatch[0].length);
    const lines = afterDesc.split(/\r?\n/);
    const collected: string[] = [];
    for (const line of lines) {
      if (line.match(/^\s+\S/)) {
        // Indented content line
        collected.push(line.trim());
      } else if (line.trim() === '' && collected.length > 0) {
        // Blank line within the scalar — folded `>` folds blank lines to '\n'
        // but for our single-line description we just ignore trailing blanks.
        break;
      } else if (collected.length > 0) {
        // Non-indented, non-empty line — end of block scalar
        break;
      }
    }
    description = collected.join(' ').trim();
  } else {
    description = inline;
  }

  return { name, description };
}

const { name, description } = parseFrontmatter(raw);

// --- Write output ---------------------------------------------------------------

const generated = `// AUTO-GENERATED by scripts/sync-skill.ts from .claude/skills/nehroai-admin/SKILL.md — do not edit by hand; run \`pnpm skill:sync\`.

export const SKILL_NAME = ${JSON.stringify(name)};
export const SKILL_DESCRIPTION = ${JSON.stringify(description)};
export const SKILL_MARKDOWN = ${JSON.stringify(raw)};
`;

fs.writeFileSync(outPath, generated, 'utf-8');

const bytes = Buffer.byteLength(raw, 'utf-8');
console.log(`skill:sync  name="${name}"  bytes=${bytes}  → lib/admin/skill-guide.ts`);
